# Generated by Django 2.2.13 on 2020-12-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_metadata_modellog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=32)),
                ('model_version', models.CharField(default='', max_length=32)),
                ('project', models.CharField(default='', max_length=32)),
                ('model_card', models.TextField(default='', max_length=1000)),
            ],
            options={
                'unique_together': {('model', 'project')},
            },
        ),
    ]
