# Generated by Django 2.2.13 on 2020-12-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20201219_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcard',
            name='caveats_and_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelcard',
            name='ethical_consideration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelcard',
            name='factors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelcard',
            name='intended_uses',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelcard',
            name='metrics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='modelcard',
            name='model_details',
            field=models.TextField(blank=True),
        ),
    ]
