# Generated by Django 2.2.13 on 2020-12-21 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20201221_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 21, 10, 39, 16, 444152, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
