# Generated by Django 2.2.13 on 2020-12-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_modelcard_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcard',
            old_name='created_at',
            new_name='uploaded',
        ),
        migrations.AddField(
            model_name='modelcard',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
